CREATE TABLE [dbo].[Replies]
(
	[CreatedAt] DATETIME2(7) NOT NULL DEFAULT GETDATE(),
	[Id] NVARCHAR(32) NOT NULL PRIMARY KEY,
	[Text] NVARCHAR(MAX) NOT NULL,
	[AuthorId] NVARCHAR(32) NOT NULL,
	[TopicId] NVARCHAR(32) NOT NULL, 
    CONSTRAINT [FK_Replies_Users] FOREIGN KEY ([AuthorId]) REFERENCES [Users]([Id]) ON DELETE CASCADE, 
    CONSTRAINT [FK_Replies_Topics] FOREIGN KEY ([TopicId]) REFERENCES [Topics]([Id]) ON DELETE CASCADE
)
