CREATE TABLE [dbo].[Users]
(
	[CreatedAt] DATETIME2(7) NOT NULL DEFAULT GETDATE(),
	[Id] NVARCHAR(32) NOT NULL PRIMARY KEY,
	[Username] NVARCHAR(255) NOT NULL,
	[FirstName] NVARCHAR(255) NULL,
	[LastName] NVARCHAR(255) NULL,
	[PasswordHash] NVARCHAR(48) NOT NULL,
	[ImageUrl] NVARCHAR(255)
)

GO

CREATE UNIQUE INDEX [IX_Users_Username] ON [dbo].[Users] ([Username])
