CREATE TABLE [dbo].[UserRoles]
(
	[CreatedAt] DATETIME2(7) NOT NULL DEFAULT GETDATE(),
	[UserId] NVARCHAR(32) NOT NULL,
	[RoleId] NVARCHAR(32) NOT NULL, 
    CONSTRAINT [PK_UserRoles] PRIMARY KEY ([UserId], [RoleId]), 
    CONSTRAINT [FK_UserRoles_Users] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_UserRoles_Roles] FOREIGN KEY ([RoleId]) REFERENCES [Roles]([Id]) ON DELETE CASCADE
)
